Add nighly feed back

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -46,34 +46,57 @@ jobs:
           path: ${{github.workspace}}/artifacts/packages/Avalonia.Xpf.Controls.WebView.*.nupkg
           retention-days: 1
 
-  publish-xpf-release:
+  publish-nightly-release:
     runs-on: ubuntu-latest
     needs: build
-    if: github.event_name == 'workflow_dispatch'
+    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/')
     steps:
 
-    - name: Check branch validity
-      if: ${{ !startsWith(github.ref, 'refs/heads/release/') }}
-      run: |
-          echo "Error: stable_release can only be run on 'release/*' branches."
-          exit 1
+      - uses: actions/download-artifact@v4
+        with:
+            name: xpf
+            path: ./nupkgs
+      - uses: actions/download-artifact@v4
+        with:
+            name: avalonia
+            path: ./nupkgs
 
-    - uses: actions/download-artifact@v4
-      with:
-        name: xpf
-        path: ./nupkgs
+      - name: Publish Nightly release
+        run: dotnet nuget push ./nupkgs/**/*.nupkg --api-key ${{secrets.NIGHTLY_FEED_API_KEY}} --source https://nuget-feed-nightly.avaloniaui.net/v3/index.json
 
-    - name: Publish XPF release
-      if: ${{ inputs.nuget }}
-      run: dotnet nuget push ./nupkgs/**/*.nupkg  --api-key ${{secrets.baget_api_key}} --source ${{ vars.BAGET_API_URL }}
-
-    - name: Clean packages
-      if: always()
-      run: rm -rf ./nupkgs
+      - name: Clean packages
+        if: always()
+        run: rm -rf ./nupkgs
+    
+#  need a feed with access to from "ubuntu-latest" runners
+#  publish-xpf-release:
+#    runs-on: ubuntu-latest
+#    needs: build
+#    if: github.event_name == 'workflow_dispatch'
+#    steps:
+#
+#    - name: Check branch validity
+#      if: ${{ !startsWith(github.ref, 'refs/heads/release/') }}
+#      run: |
+#          echo "Error: stable_release can only be run on 'release/*' branches."
+#          exit 1
+#
+#    - uses: actions/download-artifact@v4
+#      with:
+#        name: xpf
+#        path: ./nupkgs
+#
+#    - name: Publish XPF release
+#      if: ${{ inputs.nuget }}
+#      run: dotnet nuget push ./nupkgs/**/*.nupkg  --api-key ${{secrets.baget_api_key}} --source ${{ vars.BAGET_API_URL }}
+#
+#    - name: Clean packages
+#      if: always()
+#      run: rm -rf ./nupkgs
 
   publish-accelerate-release:
     runs-on: ubuntu-latest
-    needs: [build, publish-xpf-release]
+    needs: build
     if: github.event_name == 'workflow_dispatch'
     steps:
 
